export const SubjectTopics = {
    "Physics": [
        "div AS Level",
        "Physical quantities and units",
        "Kinematics",
        "Dynamics",
        "Forces, density and pressure",
        "Work, energy and power",
        "Deformation of solids",
        "Waves",
        "Superposition",
        "Electricity",
        "D.C. circuits",
        "Particle physics",
        "div A Level",
        "Motion in a circle",
        "Gravitational fields",
        "Temperature",
        "Ideal gases",
        "Thermodynamics",
        "Oscillations",
        "Electric fields",
        "Alternating currents",
        "Quantum physics",
        "Nuclear physics",
        "Medical physics",
        "Astronomy and cosmology"
    ],
    "Biology": [
        "div AS Level",
        "Cell structure",
        "Biological molecules",
        "Enzymes",
        "Cell membranes and transport",
        "The mitotic cell cycle",
        "Nucleic acids and protein synthesis",
        "Transport in plants",
        "Transport in mammals",
        "Gas exchange",
        "Infectious diseases",
        "Immunity",
        "div A Level",
        "Energy and respiration",
        "Photosynthesis",
        "Homeostasis",
        "Control and coordination",
        "Inheritance",
        "Selection and evolution",
        "Classification, biodiversity and conservation",
        "Genetic technology"
    ],
    "Chemistry": [
        "Atoms, molecules and stoichiometry",
        "Atomic structure",
        "Chemical bonding",
        "States of matter",
        "Chemical energetics",
        "Electrochemistry",
        "Equilibria",
        "Reaction kinetics",
        "The periodic table: Chemical periodicity",
        "Group 2",
        "Group 17",
        "Introduction to the Chemistry of transition elements",
        "Nitrogen and sulfer",
        "Introduction to organic chemistry",
        "Hydrocarbons",
        "Hydroxy compounds",
        "Carbonyl Compounds",
        "Carboxylic acids and derivatives",
        "Nitrogen compounds",
        "Polymerisation",
        "Analytical techniques",
        "Organic synthesis"
    ],
    "Mathematics": [
        "div Pure Mathematics 1",
        "Quadratics",
        "Functions",
        "Coordinate geometry",
        "Circular measure",
        "Trigonometry",
        "Series",
        "Differentiation",
        "Integration",
        "Algebra",
        "div Pure Mathematics 3",
        "Further Algebra",
        "Logarithmic and exponential functions",
        "Further trigonometry",
        "Further differentiation",
        "Further integration",
        "Numerical solution of equations",
        "Vectors",
        "Differential equations",
        "Complex numbers",
        "div Mechanics",
        "Forces and equilibrium",
        "Kinematics and motion in a straight line",
        "Momentum",
        "Newton's laws of motion",
        "Work, energy and power",
        "div Statistics 1",
        "Representation of data",
        "Permutations and combinations",
        "Probability",
        "Discrete random variables",
        "The normal distribution",
        "div Statistics 2",
        "The Poisson distribution",
        "Linear combinations of random variables",
        "Continuous random variables",
        "Sampling and estimation",
        "Hypothesis tests",
    ],
    "Computer Science": [
        "div AS Level",
        "Information representation",
        "Communication",
        "Hardware",
        "Processor fundamentals",
        "System software",
        "Security, privacy and data integrity",
        "Ethics and ownership",
        "Databases",
        "Algorithm design and problem-solving",
        "Data types and structures",
        "Programming (Pseudocode)",
        "Software development",
        "div A Level",
        "Data representation",
        "Communication and internet technologies",
        "Hardware and virtual machines",
        "Security",
        "Artificial intelligence",
        "Computational thinking and problem-solving",
        "Further programming (Python)"
    ],
}