export const SubjectTopics = {
    "Physics": [
        "Physical quantities and units",
        "Kinematics",
        "Dynamics",
        "Forces, density and pressure",
        "Work, energy and power",
        "Deformation of solids",
        "Waves",
        "Superposition",
        "Electricity",
        "D.C. circuits",
        "Particle physics",
        "Circular motion",
        "Gravitational fields",
        "Temperature",
        "Ideal gases",
        "Thermodynamics",
        "Oscillations",
        "Electric fields",
        "Capacitance",
        "Magnetic fields",
        "Alternating currents",
        "Quantum physics",
        "Nuclear physics",
        "Medical imaging",
        "Astronomy and cosmology",
    ],
    "Mathematics": [
        "Algebra",
        "Functions",
        "Trigonometry",
        "Calculus",
        "Vectors",
        "Statistics",
        "Probability",
        "Differential equations",
        "Complex numbers",
        "Numerical methods",
        "Coordinate geometry",
        "Series",
        "Transforms",
        "Mechanics",
        "Discrete mathematics",
        "Linear programming",
        "Geometry",
        "Graphs",
        "Matrices",
        "Sets",
        "Logic",
        "Number theory",
        "Combinatorics",
        "Topology",
        "Algorithms",
    ],
    "Information Technology": [
        "Data representation",
        "Communication and Internet technologies",
        "Hardware",
        "Software development",
        "Program construction",
        "Algorithms",
        "Data structures",
        "Computer organisation and architecture",
        "Database systems",
        "Computer networks",
        "Web technologies",
        "Modelling and simulation",
        "Artificial intelligence",
        "Robotics",
        "Cyber security",
        "Quantum computing",
        "Ethical, legal and social issues",
        "Impact of IT",
        "Programming with Python"
    ],
}